
package backend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IndexManagerService", targetNamespace = "http://test", wsdlLocation = "http://localhost:8080/ws_war_exploded/IndexManager?wsdl")
public class IndexManagerService
    extends Service
{

    private final static URL INDEXMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException INDEXMANAGERSERVICE_EXCEPTION;
    private final static QName INDEXMANAGERSERVICE_QNAME = new QName("http://test", "IndexManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws_war_exploded/IndexManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INDEXMANAGERSERVICE_WSDL_LOCATION = url;
        INDEXMANAGERSERVICE_EXCEPTION = e;
    }

    public IndexManagerService() {
        super(__getWsdlLocation(), INDEXMANAGERSERVICE_QNAME);
    }

    public IndexManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INDEXMANAGERSERVICE_QNAME, features);
    }

    public IndexManagerService(URL wsdlLocation) {
        super(wsdlLocation, INDEXMANAGERSERVICE_QNAME);
    }

    public IndexManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INDEXMANAGERSERVICE_QNAME, features);
    }

    public IndexManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IndexManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IndexManager
     */
    @WebEndpoint(name = "IndexManagerPort")
    public IndexManager getIndexManagerPort() {
        return super.getPort(new QName("http://test", "IndexManagerPort"), IndexManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IndexManager
     */
    @WebEndpoint(name = "IndexManagerPort")
    public IndexManager getIndexManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test", "IndexManagerPort"), IndexManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INDEXMANAGERSERVICE_EXCEPTION!= null) {
            throw INDEXMANAGERSERVICE_EXCEPTION;
        }
        return INDEXMANAGERSERVICE_WSDL_LOCATION;
    }

}
